version: "3.5"
services:
  atila:
    image: ghcr.io/web-tech-tw/arona:main
    networks:
      - nymph-stack
    volumes:
      - "./config.yaml:/workplace/config.yaml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.group=nymph-stack"
      - "traefik.http.routers.atila.rule=PathPrefix(`/recv/atila`)"
      - "traefik.http.services.atila.loadbalancer.server.port=3000"
      - "traefik.http.services.atila.loadbalancer.healthcheck.path=/heart"
      - "traefik.http.services.atila.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.routers.atila.middlewares=atila-strip-prefix"
      - "traefik.http.middlewares.atila-strip-prefix.stripprefix.prefixes=/atila"
    restart: unless-stopped

networks:
  nymph-stack:
    external:
      name: nymph-stack
