version: "3.5"
services:
  inte:
    image: ghcr.io/web-tech-tw/freya:main
    networks:
      - nymph-stack
    labels:
      - "traefik.enable=true"
      - "traefik.group=nymph-stack"
      - "traefik.http.routers.freya-inte.rule=PathPrefix(`/freya`)"
      - "traefik.http.services.freya-inte.loadbalancer.server.port=80"
      - "traefik.http.services.freya-inte.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.freya-inte.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.routers.freya-inte.middlewares=freya-inte-strip-prefix"
      - "traefik.http.middlewares.freya-inte-strip-prefix.stripprefix.prefixes=/freya"
    restart: unless-stopped

  recv:
    image: ghcr.io/web-tech-tw/freya.recv:main
    container_name: freya-recv
    environment:
      APP_CONFIGURED: "1"
    env_file:
      - config.env
    networks:
      - sara
      - nymph-stack
    volumes:
      - ../010-sara/keypair_public.pem:/workplace/keypair_public.pem:ro
    labels:
      - "traefik.enable=true"
      - "traefik.group=nymph-stack"
      - "traefik.http.routers.freya-recv.rule=PathPrefix(`/recv/freya`)"
      - "traefik.http.services.freya-recv.loadbalancer.server.port=3000"
      - "traefik.http.services.freya-recv.loadbalancer.healthcheck.path=/robots.txt"
      - "traefik.http.services.freya-recv.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.routers.freya-recv.middlewares=freya-recv-strip-prefix"
      - "traefik.http.middlewares.freya-recv-strip-prefix.stripprefix.prefixes=/recv/freya"
    restart: unless-stopped

networks:
  sara:
    external:
      name: sara
  nymph-stack:
    external:
      name: nymph-stack
