version: "3"
services:
  ironnect:
    image: ghcr.io/ai-tech-tw/ironnect:main
    environment:
      SCRIPT_NAME: "/recv/openai"
    networks:
      - nymph-stack
    volumes:
      - "./config.local.py:/workplace/config.local.py:ro"
      - "./models:/workplace/models:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.group=nymph-stack"
      - "traefik.http.routers.ironnect.rule=PathPrefix(`/recv/openai`)"
      - "traefik.http.services.ironnect.loadbalancer.server.port=8000"
      - "traefik.http.services.ironnect.loadbalancer.healthcheck.path=/recv/openai/"
      - "traefik.http.services.ironnect.loadbalancer.healthcheck.interval=30s"
    restart: unless-stopped

networks:
  nymph-stack:
    external:
      name: nymph-stack
