version: "3"
services:
  proxy:
    image: ghcr.io/ai-tech-tw/ironnect:main
    container_name: ironnect
    environment:
      SCRIPT_NAME: "/recv/openai"
    volumes:
      - "./config.py:/workplace/config.local.py:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.group=nymph-stack"
      - "traefik.http.routers.ironnect.rule=PathPrefix(`/recv/openai`)"
      - "traefik.http.services.ironnect.loadbalancer.server.port=8000"
      - "traefik.http.services.ironnect.loadbalancer.healthcheck.path=/recv/openai"
      - "traefik.http.services.ironnect.loadbalancer.healthcheck.interval=30s"
    restart: always
