version: "3.5"
services:
  rustic:
    container_name: nymph-rustic
    build:
      context: ./rustic
    volumes:
      - ./config.toml:/etc/rustic/rustic.toml:ro
      - /etc:/srv/sys-etc:rw
      - /srv:/srv/sys-srv:rw
    restart: unless-stopped
